export const referencesContent = {
  hero: {
    title: "Våra kundreferenser",
    subtitle: "Se vad vi har åstadkommit tillsammans med våra kunder i Raseborg och omgivande kommuner.",
  },

  categories: ["Alla", "Villa", "Lantbruk", "Företag"],

  projects: [
    {
      id: 1,
      title: "Villa i Ekenäs",
      category: "Villa",
      location: "Ekenäs, Raseborg",
      power: "6.3 kWp",
      panels: 14,
      year: 2024,
      description: "Modern villa med sydvänt tak. Systemet täcker familjens hela elbehov under sommarhalvåret.",
      image: "https://images.unsplash.com/photo-1509391366360-2e959784a276?w=800",
      quote: "Vi är otroligt nöjda med installationen. Solklart var professionella från start till mål.",
      customer: "Familjen Lindström",
    },
    {
      id: 2,
      title: "Lantgård i Snappertuna",
      category: "Lantbruk",
      location: "Snappertuna, Raseborg",
      power: "45 kWp",
      panels: 100,
      year: 2024,
      description: "Stort system installerat på ladugårdstak. Producerar el till hela gårdens verksamhet.",
      image: "https://images.unsplash.com/photo-1559302504-64aae6ca6b6d?w=800",
      quote: "Fantastisk investering för vår gård. Elkostnaderna har minskat drastiskt.",
      customer: "Karlsson Lantbruk",
    },
    {
      id: 3,
      title: "Industrihall i Karis",
      category: "Företag",
      location: "Karis, Raseborg",
      power: "120 kWp",
      panels: 267,
      year: 2023,
      description: "Ett av våra största projekt. Systemet försörjer hela produktionsanläggningen.",
      image: "https://images.unsplash.com/photo-1497440001374-f26997328c1b?w=800",
      quote: "Solklart levererade i tid och enligt budget. Mycket professionellt arbete.",
      customer: "Karis Industri Ab",
    },
    {
      id: 4,
      title: "Radhus i Billnäs",
      category: "Villa",
      location: "Billnäs, Raseborg",
      power: "4.5 kWp",
      panels: 10,
      year: 2024,
      description: "Kompakt system anpassat för radhustak med begränsad yta.",
      image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800",
      quote: "Även med begränsat utrymme fick vi ett effektivt system som gör skillnad.",
      customer: "Erik Sundberg",
    },
    {
      id: 5,
      title: "Jordbruksfastighet i Tenala",
      category: "Lantbruk",
      location: "Tenala, Raseborg",
      power: "32 kWp",
      panels: 71,
      year: 2023,
      description: "Installation på ekonomibyggnad med optimalt söderläge.",
      image: "https://images.unsplash.com/photo-1508514177221-188b1cf16e9d?w=800",
      quote: "Bästa beslutet vi tagit för gården. Rekommenderar Solklart till alla.",
      customer: "Tenala Gård",
    },
    {
      id: 6,
      title: "Kontorsbyggnad i Hangö",
      category: "Företag",
      location: "Hangö",
      power: "25 kWp",
      panels: 56,
      year: 2023,
      description: "Modernt kontorshus med fokus på hållbarhet och energieffektivitet.",
      image: "https://images.unsplash.com/photo-1466611653911-95081537e5b7?w=800",
      quote: "Solcellerna var en viktig del av vår hållbarhetsstrategi.",
      customer: "Hangö Business Center",
    },
  ],

  stats: {
    title: "Vårt avtryck",
    items: [
      { value: "300+", label: "Genomförda installationer" },
      { value: "2 MW", label: "Total installerad effekt" },
      { value: "~300 ton", label: "CO₂ besparat per år" },
      { value: "98%", label: "Kundnöjdhet" },
    ],
  },
};
